fix home/header login button
SELab-2/UGent-3 pull request #228
Opened 2024-04-23 09:45 UTC by warreprovoost

Closes #227 #241

2024-04-23 12:24 UTC, Vucis commented on frontend/src/utils/fetches/FetchMe.ts
> +    if(response.status == 200){
stay consistent with spaces: if() and then later catch () and then }else {

2024-04-23 12:29 UTC, Vucis approved these changes

2024-04-23 16:29 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +    if (me.role !== "UNKNOWN") {
No, this must check if person is logged in, don't check the role. Or check the role inside the `isLoggedIn` function

2024-04-23 16:32 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +                  onClick={() => (window.location.href = `${API_URL}/logout`)}
Don't do `window.location.href` there are functions made for redirects, `navigate`

2024-04-23 16:35 UTC, AronBuzogany commented on frontend/src/components/Header/Login.tsx
> +      {" "}
What's this for

2024-04-23 16:36 UTC, AronBuzogany commented on frontend/src/pages/home/HomePages.tsx
> +  if (me === "UNKNOWN") {
Same here, make a function that checks if someone is logged in, the meaning of roles can change which can cause this to break

2024-04-23 16:37 UTC, AronBuzogany commented on frontend/src/utils/fetches/FetchMe.ts
> +      return { role: "UNKNOWN" };
you can change this to `loggedIn: false` for example, and above `true`

2024-04-23 16:38 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +          {me.role !== "UNKNOWN" && (
Keep the login button in the header also, that way people can log in from `404` for example page also

2024-04-26 10:31 UTC, AronBuzogany requested changes

2024-04-26 10:31 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +    if (me.role !== "UNKNOWN") {
Not solved

2024-04-26 10:31 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +                  onClick={() => (window.location.href = `${API_URL}/logout`)}
not fixed

2024-04-26 10:52 UTC, AronBuzogany approved these changes

2024-04-26 10:52 UTC, AronBuzogany commented on frontend/src/components/Header/Header.tsx
> +                <MenuItem>
Next time you can do

`<MenuItem component="a" href="..." >`

2024-04-26 10:54 UTC, merged