Seeder for easier demo and frontend testing
SELab-2/UGent-3 pull request #291
Opened 2024-04-28 11:47 UTC by JibrilExe

Step 1 update db with db_construct
Step 2 cd backend
Step 3 python -m seeder uid

No quotes needed around uid, will insert 5 courses where you are teacher and 5 where you are student into the db, with like 5-30 other students with each some submissions.

2024-04-28 13:52 UTC, Vucis requested changes

2024-04-28 13:52 UTC, Vucis commented on backend/seeder/elements.py
> +    " Computer Science",
Remove leading whitespace

2024-04-28 17:20 UTC, Vucis requested changes

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +    """Populates the db with 5 courses where my uid is teacher and 5 where he is student"""
Make this clearer by using my_uid instead of my uid, because the argument was always referred to as my_uid before

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +            session.commit()
Maybe do all of these with batch operations instead

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +    # Add students to the course
remove this comment, the docstring of the function explains what it does

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +        # Rollback
either remove this comment or explain why a rollback occurs, because you can just see a rollback happening right below this comment

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +        for _ in range(5):  # 5 courses where we are teacher
maybe use my_uid instead of we, e.g. 5 courses where my_uid is a teacher

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +            session.commit()
batch operations

2024-04-28 17:20 UTC, Vucis commented on backend/seeder/seeder.py
> +        session.commit()
batch operations

2024-04-29 11:47 UTC, Vucis requested changes

2024-04-29 11:47 UTC, Vucis commented on backend/seeder/seeder.py
> +    finally:
doesn't this always rollback because of finally?

2024-04-29 11:47 UTC, Vucis commented on backend/seeder/seeder.py
> +    while len(subscribed_students) < num_students_in_course:
you can do this with batch operations as well

2024-04-29 14:11 UTC, Vucis requested changes

2024-04-29 14:11 UTC, Vucis commented on backend/seeder/seeder.py
> +    except Exception as e:
Strange that the linter doesn't catch this, but this should be SQLAlchemyError, not a generic exception

2024-04-29 15:29 UTC, Vucis commented
Also, remove the session.close from except. Because finally will always execute so if an error occurs you'll try session.close twice

2024-04-29 19:55 UTC, AronBuzogany requested changes

2024-04-29 19:55 UTC, AronBuzogany commented on backend/seeder/seeder.py
> +        num_deadlines = random.randint(1, 3)
also have projects without deadlines

2024-04-30 15:09 UTC, Vucis approved these changes

2024-04-30 17:05 UTC, AronBuzogany requested changes
seeder should be executable by doing

`python seeder uid`

of

`python seeder.py uid`

2024-05-03 16:37 UTC, AronBuzogany requested changes

2024-05-04 09:20 UTC, AronBuzogany approved these changes

2024-05-04 09:21 UTC, merged