Fix status on ProjectCards
SELab-2/UGent-3 pull request #307
Opened 2024-05-03 10:25 UTC by warreprovoost

Closes #306

2024-05-03 15:27 UTC, Vucis approved these changes

2024-05-04 07:57 UTC, AronBuzogany requested changes

2024-05-04 07:57 UTC, AronBuzogany commented on frontend/public/locales/nl/translation.json
> +    "RUNNING": "Aan het lopen ",
Remove whitespace

2024-05-04 08:39 UTC, AronBuzogany approved these changes

2024-05-04 08:40 UTC, merged