Added readme for user guide
SELab-2/UGent-3 pull request #330
Opened 2024-05-04 17:50 UTC by Gerwoud

The user guide doesn't contain a readme atm, it contains a simple one after the introduction of this PR

2024-05-05 09:11 UTC, Vucis requested changes

2024-05-05 09:11 UTC, Vucis commented on documentation/documentation/README.md
> +Project peristerónas has a lot of features, therefor a detailed user guide is available to consult.
therefor -> therefore

2024-05-05 09:11 UTC, Vucis commented on documentation/documentation/README.md
> +  A static version will be build that you can acces in the directory `build/`, you can then run the static site by using the command:
build -> built
acces -> access

2024-05-05 09:11 UTC, Vucis commented on documentation/documentation/README.md
> +  When you're ready to deploy run the following command to run the proper version of the site:
...deploy run ... -> ...deploy, run ...

2024-05-06 11:12 UTC, Gerwoud commented on documentation/documentation/README.md
> +  When you're ready to deploy run the following command to run the proper version of the site:
https://github.com/SELab-2/UGent-3/pull/330/commits/47149f65336f985a68ab6286295ab44e83de8584

2024-05-06 11:12 UTC, Gerwoud commented on documentation/documentation/README.md
> +  A static version will be build that you can acces in the directory `build/`, you can then run the static site by using the command:
https://github.com/SELab-2/UGent-3/pull/330/commits/47149f65336f985a68ab6286295ab44e83de8584

2024-05-06 11:12 UTC, Gerwoud commented on documentation/documentation/README.md
> +Project peristerónas has a lot of features, therefor a detailed user guide is available to consult.
https://github.com/SELab-2/UGent-3/pull/330/commits/47149f65336f985a68ab6286295ab44e83de8584

2024-05-06 12:59 UTC, Vucis approved these changes

2024-05-06 12:59 UTC, merged