changed documentation location from documentation/documentation/ to documentation/
SELab-2/UGent-3 pull request #337
Opened 2024-05-06 12:17 UTC by Gerwoud

title

2024-05-06 12:58 UTC, Vucis approved these changes

2024-05-06 17:56 UTC, AronBuzogany approved these changes

2024-05-06 17:56 UTC, AronBuzogany requested changes
conflicts jong

2024-05-09 07:28 UTC, AronBuzogany approved these changes

2024-05-09 07:28 UTC, merged