Teacher is now listed as admin on course page
SELab-2/UGent-3 pull request #349
Opened 2024-05-12 12:24 UTC by JibrilExe

Reworked useEffect of admins and students Me page fetching so they dont add users twice which resulted in duplicate listing

Fixes #234

2024-05-12 14:19 UTC, Vucis approved these changes

2024-05-12 14:43 UTC, AronBuzogany requested changes

2024-05-12 14:43 UTC, AronBuzogany commented on frontend/src/components/Courses/CourseDetailTeacher.tsx
> +    const fetchAdminData = async () => {
Doing this will define the function on every effect trigger

2024-05-12 14:43 UTC, AronBuzogany commented on frontend/src/components/Courses/CourseDetailTeacher.tsx
> +    const fetchStudentData = async () => {
same here

2024-05-15 18:52 UTC, AronBuzogany requested changes
Page won't load

2024-05-18 08:45 UTC, AronBuzogany approved these changes

2024-05-18 14:51 UTC, merged