Only shows create course button when you have privilege to see it
SELab-2/UGent-3 pull request #353
Opened 2024-05-12 14:41 UTC by AronBuzogany

Closes #265

2024-05-13 08:22 UTC, Vucis approved these changes

2024-05-14 09:47 UTC, JibrilExe approved these changes

2024-05-14 11:09 UTC, JibrilExe requested changes
First fix conflicts or no merging eh

2024-05-21 09:37 UTC, ArnoutAllaert commented
Solve merge conflict. 😄

2024-05-23 07:08 UTC, JibrilExe approved these changes

2024-05-23 07:27 UTC, merged