Project form/drag drop translations
SELab-2/UGent-3 pull request #359
Opened 2024-05-14 09:12 UTC by JibrilExe

Fixes #327

2024-05-14 10:33 UTC, Vucis approved these changes

2024-05-14 13:59 UTC, Gerwoud commented on frontend/public/locales/en/projectformTranslation.json
> +    "dragDropHere" :"Drag & Drop a File Here",
In the English version File and Here are capitalized while it's not in the Dutch version, better to keep it consistent.

2024-05-14 14:00 UTC, Gerwoud requested changes

2024-05-14 14:00 UTC, Gerwoud commented on frontend/public/locales/en/projectformTranslation.json
> +    "dragDropHere" :"Drag & Drop a File Here",
In the English version File and Here are capitalized while it's not in the Dutch version, better to keep it consistent.

2024-05-16 07:02 UTC, Gerwoud approved these changes
:fire:

2024-05-16 07:02 UTC, merged